#ifndef SOCKETADAPTERTOMESSAGETABLES_H_INCLUDED
#define SOCKETADAPTERTOMESSAGETABLES_H_INCLUDED

void * SocketAdapterToMessageTable_Thread(void * ptr);

#endif // SOCKETADAPTERTOMESSAGETABLES_H_INCLUDED
